# Generated by Django 3.0.6 on 2022-09-05 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 5, 8, 33, 3, 847690), verbose_name='date published'),
        ),
    ]
